"""phase5 enterprise layer

Revision ID: 167131b5791b
Revises: 72dc2fd0b8f8
Create Date: 2026-03-19 08:07:18.273126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167131b5791b'
down_revision: Union[str, None] = '72dc2fd0b8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_severity_created', table_name='alerts')
    op.create_foreign_key(None, 'alerts', 'bins', ['bin_id'], ['bin_id'], ondelete='CASCADE')
    op.drop_index('ix_classifications_bin_ts_id', table_name='classifications')
    op.create_foreign_key(None, 'classifications', 'bins', ['bin_id'], ['bin_id'], ondelete='CASCADE')
    op.drop_index('ix_decision_items_run_priority', table_name='decision_items')
    op.drop_index('ix_device_heartbeats_device_id_ts', table_name='device_heartbeats')
    op.drop_index('ux_devices_serial_number', table_name='devices')
    op.drop_constraint('uq_organisations_slug', 'organisations', type_='unique')
    op.drop_index('ix_password_reset_user_used_expires', table_name='password_reset_codes')
    op.drop_index('ix_route_plans_ts_desc', table_name='route_plans')
    op.drop_index('ix_route_trips_plan_trip_index', table_name='route_trips')
    op.drop_index('ix_telemetry_bin_ts_id', table_name='telemetry')
    op.create_foreign_key(None, 'telemetry', 'bins', ['bin_id'], ['bin_id'], ondelete='CASCADE')
    op.drop_index('ix_users_email_active', table_name='users')
    op.create_index(op.f('ix_work_orders_alert_id'), 'work_orders', ['alert_id'], unique=False)
    op.create_index(op.f('ix_work_orders_bin_id'), 'work_orders', ['bin_id'], unique=False)
    op.create_index(op.f('ix_work_orders_due_at'), 'work_orders', ['due_at'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_route_plan_id'), 'work_orders', ['route_plan_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_route_plan_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_due_at'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_bin_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_alert_id'), table_name='work_orders')
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.create_index('ix_telemetry_bin_ts_id', 'telemetry', ['bin_id', sa.text('ts DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_route_trips_plan_trip_index', 'route_trips', ['plan_id', 'trip_index'], unique=False)
    op.create_index('ix_route_plans_ts_desc', 'route_plans', [sa.text('ts DESC')], unique=False)
    op.create_index('ix_password_reset_user_used_expires', 'password_reset_codes', ['user_id', 'used', sa.text('expires_at DESC')], unique=False)
    op.create_unique_constraint('uq_organisations_slug', 'organisations', ['slug'])
    op.create_index('ux_devices_serial_number', 'devices', ['serial_number'], unique=True)
    op.create_index('ix_device_heartbeats_device_id_ts', 'device_heartbeats', ['device_id', 'ts'], unique=False)
    op.create_index('ix_decision_items_run_priority', 'decision_items', ['run_id', sa.text('priority_score DESC'), 'bin_id'], unique=False)
    op.drop_constraint(None, 'classifications', type_='foreignkey')
    op.create_index('ix_classifications_bin_ts_id', 'classifications', ['bin_id', sa.text('ts DESC'), sa.text('id DESC')], unique=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_index('ix_alerts_status_severity_created', 'alerts', ['status', 'severity', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
